name: Retrieve Secrets from Azure Key Vault

on:
  workflow_dispatch:
    inputs:
      key-names:
        description: 'Comma-separated list of key names to retrieve from Azure Key Vault'
        required: true

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve Secrets from Azure Key Vault
        id: retrieve-secrets
        uses: ./.github/actions/retrieve-secrets
        with:
          key-names: ${{ github.event.inputs['key-names'] }}

      - name: Display Retrieved Secrets
        run: |
          IFS=',' read -ra KEYS <<< "${{ github.event.inputs['key-names'] }}"
          for key in "${KEYS[@]}"; do
            value="${{ steps.retrieve-secrets.outputs[$key] }}"
            if [ -n "$value" ]; then
              echo "Retrieved secret for $key successfully."
            else
              echo "No secret found for $key."
            fi
          done
